---
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  default: minor
template: |
  ## [UNRELEASED]

  ### What's Changed
  
  _(most recent changes are listed on top):_
  $CHANGES
