name: PHP 7.0

on:
  push:

permissions:
  contents: read

jobs:
  setup:
    name: PHP Compatibility 7.0
    runs-on: ubuntu-latest
    permissions:
      contents: read # for checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: PHP Setup 
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0-'
          coverage: none

      - name: php-compatibility run
        uses: pantheon-systems/phpcompatibility-action@v1
        with:
          test-versions: '7.0-'
          paths: ${{ github.workspace }}/Plugin.php ${{ github.workspace }}/Controller/ ${{ github.workspace }}/Locale/ ${{ github.workspace }}/Model/ ${{ github.workspace }}/Helper/ ${{ github.workspace }}/Template/
